apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nodeapp
        env:
        - name: APP_ENV
          value: "development"
        - name: APP_VERSION
          value: "1.0.0"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
