apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nodeapp
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_VERSION
          value: "1.0.0"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
