apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nodeapp
        env:
        - name: APP_ENV
          value: "staging"
        - name: APP_VERSION
          value: "1.0.0"
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
