apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:developer, applications, get, frontend-team/*
    p, role:developer, applications, sync, frontend-team/*
    p, role:developer, applications, list, frontend-team/*
    p, role:developer, logs, get, frontend-team/*
    p, role:readonly, applications, get, */*
    p, role:readonly, applications, list, */*
    g, alice, role:developer
    g, bob, role:readonly
