apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://pelluri-berrypi1.tail8e4559.ts.net
  accounts.alice: login
  accounts.bob: login
