apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: kustomize-app
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
