apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/spelluri/argocd-apps  # YOUR repo!
    targetRevision: HEAD
    path: manifests/guestbook                          # YOUR manifests!
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
       prune: true
       selfheal: true
    syncOptions:
      - CreateNamespace=true
