apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: frontend-team
  source:
    repoURL: https://github.com/spelluri/argocd-apps
    targetRevision: HEAD
    path: manifests/nodeapp/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: nodeapp-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
